#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.5 (standalone edition) on Mon Jan 07 18:13:42 2013

import wx
from model.StockData import *
from model.DataManager import *
import random
from util.draw import *
# begin wxGlade: extracode
# end wxGlade


class AnalysisPanel(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: AnalysisPanel.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)

        self.__set_properties()
        self.__do_layout()    


    
        
        
        
        
    def __set_properties(self):
        # begin wxGlade: AnalysisPanel.__set_properties
        self.SetSize((588, 422))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: AnalysisPanel.__do_layout
        pass
        # end wxGlade

        

# end of class AnalysisPanel
