#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.5 (standalone edition) on Mon Jan 07 18:13:42 2013

import wx
from model.quote_realtime import *
from model.DataManager import *
import random
from util.draw import *
from util.czsc import *
# begin wxGlade: extracode
# end wxGlade


class CandlePanel(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: CandlePanel.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)

        self.__set_properties()
        self.__do_layout() 
        
        self.Bind(wx.EVT_PAINT, self.OnPaint)  
        self.Bind(wx.EVT_ERASE_BACKGROUND, self.EraseBack)
        self.data = None 


    
    def EraseBack(self, evt):
        pass
       
    def OnPaint(self, evt):
        dc = wx.PaintDC(self)
        dc.Clear()
        if self.data is None:
            dc.DrawText("data is not available", 0, 0) 
        else:
                 
            draw_candle(dc, self.data)
            czsc = ChanlunCore()
            czsc.Draw(dc, self.data)
           
        
        
    def __set_properties(self):
        # begin wxGlade: CandlePanel.__set_properties
        self.SetSize((588, 422))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: CandlePanel.__do_layout
        pass
        # end wxGlade

        

# end of class CandlePanel
